### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by shazow** [thousandetherhomepage/ketherstatic#1]
- [x] Output rinkeby and mainnet
- [ ] Archive revisions for posterity (only when something changes)
- [x] Host the image/json somewhere public

**Comment by mveytsman** [comment]
@shazow 

- https://storage.googleapis.com/ketherhomepage/rinkeby.json
- https://storage.googleapis.com/ketherhomepage/rinkeby.png
- https://storage.googleapis.com/ketherhomepage/mainnet.json
- https://storage.googleapis.com/ketherhomepage/mainnet.png

**Comment by shazow** [comment]
@mveytsman Access denied.

**Comment by mveytsman** [comment]
@shazow ACL took a second to propagate, try again
