### ISSUE TITLE
How can I use this on s3?

### ISSUE THREAD

**Issue by jesterxd** [thousandetherhomepage/ketherstatic#18]
Please excuse my ignorance, I am new to Go and cloud storage. I was wondering how I could run this with AWS S3 instead of Google Cloud Storage? Do I just have to edit the authentication part? Or else what parts must I edit? Is this code specific to only Google Cloud Storage?

Thanks:)

**Comment by shazow** [comment]
@jesterxd Hiya, you'll have to fork the code and make the changes to write to S3. :)

We wrote this for ourselves to create a static cache, and we happened to use Google Cloud for that. If you need something different, you'll need to make the modifications you need.

No plans to add support for S3, since we don't use S3 personally, but we'd accept a PR if you can do it in a backwards compatible way.

**Comment by jesterxd** [comment]
>We wrote this for ourselves to create a static cache, and we happened to use Google Cloud for that.

I seem to be mistaken, I thought this was the only way the data was loaded. Because `ketherhomepage` loads it from `https://storage.googleapis.com/storage.thousandetherhomepage.com/mainnet.png` and `https://storage.thousandetherhomepage.com/mainnet.json`.  
According to my understanding, the data exists on the blockchain and is stored in Cloud Storage. Thousand Ether Homepage loads it from the cloud storage. Is the data stored anywhere else? If yes, how can that be accessed and loaded instead of the cache?

Thanks again :)

**Comment by shazow** [comment]
Ah yes, we only _preload_ the data from our cache. The actual data is also loaded in realtime from the Ethereum blockchain, after the cache is loaded.

You can follow the contract (linked in the footer) to here: https://etherscan.io/address/0xb5fe93ccfec708145d6278b0c71ce60aa75ef925

The code is there (and [also on Github here](https://github.com/thousandetherhomepage/ketherhomepage/)), you can interact with it directly here: https://etherscan.io/address/0xb5fe93ccfec708145d6278b0c71ce60aa75ef925#readContract

![image](https://user-images.githubusercontent.com/6292/117485811-d87b8300-af36-11eb-8f8f-09e3c5e54ae7.png)
